apiVersion: v1
kind: Service
metadata:
  name: {{ include "mvix-crm-backend-nginx.name" . }}
  labels:
    {{- include "mvix-crm-backend-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.httpPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mvix-crm-backend-nginx.selectorLabels" . | nindent 4 }}