apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mvix-crm-backend-nginx.name" . }}
  labels:
    {{- include "mvix-crm-backend-nginx.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  {{- if not .Values.nginx.autoscaling.enabled }}
  replicas: {{ .Values.nginx.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 10
  strategy:
    {{- toYaml .Values.default.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "mvix-crm-backend-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/nginx-conf: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
        {{- include "mvix-crm-backend-nginx.selectorLabels" . | nindent 8 }}
      labels:
        {{- include "mvix-crm-backend-nginx.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nginx.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.default.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name:  {{ include "mvix-crm-backend-nginx.name" . }}
          securityContext:
            {{- toYaml .Values.default.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
          - name: http
            containerPort: {{ .Values.nginx.httpPort }}
            protocol: TCP
          - name: healthz
            containerPort: {{ .Values.nginx.healthzPort }}
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: healthz
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: healthz
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 10"]          
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: "/etc/nginx/conf.d/default.conf"
            subPath: default.conf
            name: nginx-configmap
          - mountPath: "/etc/nginx/nginx.conf"
            subPath: nginx.conf
            name: nginx-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: {{ .Values.nginx.restartPolicy }}
      {{- with .Values.default.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.default.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                {{- range $key,$value := (fromYaml (include "mvix-crm-backend-nginx.selectorLabels" . ))}}
                - key: {{ $key }}
                  operator: In
                  values:
                  - {{ $value }}
                {{- end}}
              topologyKey: kubernetes.io/hostname
            weight: 100
      {{- end }}
      {{- with .Values.default.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-backend
        name: nginx-configmap
