{{- if .Values.nginx.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mvix-crm-backend-nginx.name" . }}
  labels:
    {{- include "mvix-crm-backend-nginx.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mvix-crm-backend-nginx.name" . }}
  {{- if  not (lookup "autoscaling/v2" "HorizontalPodAutoscaler" .Release.Namespace .Release.Name)}}
  minReplicas: {{ .Values.nginx.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.nginx.autoscaling.maxReplicas }}
  {{- else }}
  minReplicas: {{ (lookup "autoscaling/v2" "HorizontalPodAutoscaler" .Release.Namespace .Release.Name).spec.minReplicas }}
  maxReplicas: {{ (lookup "autoscaling/v2" "HorizontalPodAutoscaler" .Release.Namespace .Release.Name).spec.maxReplicas }}
  {{- end }}
  metrics:
    {{- if .Values.nginx.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.nginx.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.nginx.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.nginx.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}