apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mvix-crm-backend-php.name" . }}
  labels:
    {{- include "mvix-crm-backend-php.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets.backendcrm }}
  {{ $key }}: {{ $value | quote }}
{{- end -}}