apiVersion: v1
kind: Secret
metadata:
  name: crm-regcred
  labels:
    {{- include "mvix-crm-backend-php.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.backendRegcred | toJson | b64enc | quote }}