apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.scheduler.name }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
  {{- with .Values.scheduler.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "scheduler.selectorLabels" . | nindent 6 }}
  strategy:
    {{- toYaml .Values.scheduler.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "scheduler.labels" . | nindent 8 }}
    spec:
    {{- with .Values.default.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.php.image.pullPolicy }}
        name: {{ .Values.scheduler.name }}
        command:
        {{- range $value := .Values.scheduler.command }}
          - {{ $value }}
        {{- end }}
        args:
        {{- range $value := .Values.scheduler.args }}
          - {{ $value }}
        {{- end }}
        env:
        {{- with .Values.scheduler.env }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: mvix-crm-backend-php
        resources:
          {{- toYaml .Values.scheduler.resources | nindent 10 }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "php artisan config:cache; php artisan route:cache"]
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/etc/php/conf.d/memory-limit.ini
          name: php-fpm-configmap
          subPath: memory-limit.ini
        - mountPath: "/usr/local/etc/php-fpm.d/zzz-docker.conf"
          name: php-fpm-configmap
          subPath: docker.conf
      dnsPolicy: ClusterFirst
      restartPolicy: {{ .Values.scheduler.restartPolicy }}
      schedulerName: default-scheduler
      {{- with .Values.php.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.default.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.php.podSecurityContext | nindent 8 }}
      securityContext: {}
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          name: php-fpm
        name: php-fpm-configmap
